# Generated by Django 4.2.6 on 2023-10-27 19:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_project_project_name_project_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Datatable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.TextField(max_length=100)),
                ('doc_data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_date', models.CharField(default=None)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
    ]
