# Generated by Django 4.2.6 on 2023-10-28 19:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_datatable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datatable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.TextField(max_length=100)),
                ('doc_data', models.JSONField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
    ]
