# Generated by Django 4.2.6 on 2023-10-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_datatable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatable',
            name='doc_data',
        ),
    ]
