# Generated by Django 4.2.6 on 2023-10-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_datatable_created_date_datatable_doc_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatable',
            name='doc_data',
        ),
    ]
