# Generated by Django 4.2.6 on 2023-11-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_datatable_doctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='docType',
            field=models.TextField(choices=[('Schedule', 'Schedule'), ('Depot', 'Depot'), ('Terminal', 'Terminal')], default=None, max_length=100),
        ),
    ]
