# Generated by Django 4.2.6 on 2023-11-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_datatable_doctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='doc_data',
            field=models.TextField(default=None),
        ),
    ]
