# Generated by Django 4.2.6 on 2023-11-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_datatable_doc_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='doc_data',
            field=models.DateTimeField(default=None),
        ),
    ]
