# Generated by Django 4.2.6 on 2023-11-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_datatable_doc_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatable',
            name='doc_data',
        ),
    ]
