# Generated by Django 4.2.6 on 2023-12-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_datatable_doc_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatable',
            name='doc_data',
        ),
        migrations.AddField(
            model_name='project',
            name='workflow_type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='docType',
            field=models.TextField(choices=[('Schedule', 'Schedule'), ('Depot', 'Depot'), ('Terminal', 'Terminal'), ('Discom_station', 'Dscmstn'), ('Ebus_schedule', 'Ebsscdl')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
