# Generated by Django 4.2.6 on 2023-12-25 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_datatable_doc_data_project_workflow_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('short_name', models.CharField()),
                ('terminal_name', models.CharField()),
                ('latitude', models.CharField()),
                ('longitude', models.CharField()),
                ('terminal_area', models.CharField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule', models.CharField()),
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('trip_number', models.CharField()),
                ('trip_id', models.CharField(blank=True)),
                ('route_number', models.CharField()),
                ('direction', models.CharField()),
                ('start_terminal', models.CharField()),
                ('end_terminal', models.CharField()),
                ('start_time', models.CharField()),
                ('travel_time', models.CharField()),
                ('trip_distance', models.CharField()),
                ('crew_id', models.CharField(blank=True)),
                ('trip_type', models.CharField()),
                ('operator', models.CharField(blank=True)),
                ('ac_non_ac', models.CharField(blank=True)),
                ('brt_non_brt', models.CharField(blank=True)),
                ('service_type', models.CharField(blank=True)),
                ('fuel_type', models.CharField(blank=True)),
                ('bus_type', models.CharField(blank=True)),
                ('depot_id', models.CharField()),
                ('origin_point', models.CharField()),
                ('destination_point', models.CharField()),
                ('end_time', models.CharField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('short_name', models.CharField()),
                ('depot_name', models.CharField()),
                ('latitude', models.CharField()),
                ('longitude', models.CharField()),
                ('capacity', models.CharField()),
                ('Operator', models.CharField()),
                ('ac_non_ac', models.CharField()),
                ('brt_non_brt', models.CharField()),
                ('type_of_service', models.CharField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
    ]
