# Generated by Django 4.2.6 on 2023-12-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_schedule_schedule_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
    ]
