# Generated by Django 4.2.6 on 2023-12-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_depot_depot_id_terminal_terminal_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depot',
            old_name='Operator',
            new_name='operator',
        ),
        migrations.AlterField(
            model_name='depot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
