# Generated by Django 4.2.6 on 2023-12-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_operator1_depot_optor1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depot',
            old_name='optor1',
            new_name='operator',
        ),
    ]
