# Generated by Django 4.2.6 on 2023-12-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_dep_operator_depot_ooperator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depot',
            old_name='ooperator',
            new_name='operator',
        ),
    ]
