# Generated by Django 4.2.6 on 2023-12-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_ooperator_depot_operator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depot',
            old_name='operator',
            new_name='_operator',
        ),
    ]
