# Generated by Django 4.2.6 on 2023-12-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_operator_depot__operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='_operator',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='operator',
        ),
    ]
