# Generated by Django 4.2.6 on 2024-03-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_remove_depot__operator_remove_schedule_operator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="depot",
            name="short_name",
        ),
        migrations.RemoveField(
            model_name="depot",
            name="type_of_service",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="destination_point",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="origin_point",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="trip_id",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="trip_type",
        ),
        migrations.RemoveField(
            model_name="terminal",
            name="short_name",
        ),
        migrations.AddField(
            model_name="depot",
            name="bus_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="depot",
            name="fuel_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="depot",
            name="operator",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="depot",
            name="service_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="event_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="operator",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="depot",
            name="ac_non_ac",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="depot",
            name="brt_non_brt",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="depot",
            name="capacity",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="depot",
            name="depot_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="depot",
            name="latitude",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="depot",
            name="longitude",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="depot",
            name="project_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="depot",
                to="main.project",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="ac_non_ac",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="brt_non_brt",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="bus_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="crew_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="depot_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="direction",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_terminal",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="fuel_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="project_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="main.project",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="route_number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="schedule_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="service_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_terminal",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_time",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="travel_time",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="trip_distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="trip_number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="latitude",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="longitude",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="project_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terminal",
                to="main.project",
            ),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="terminal_area",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="terminal_name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
