# Generated by Django 4.2.6 on 2024-03-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_project_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_submitted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
