# Generated by Django 4.2.6 on 2024-03-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_depot_latitude_alter_depot_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='docType',
            field=models.TextField(choices=[('Schedule', 'Schedule'), ('Depot', 'Depot'), ('Terminal', 'Terminal'), ('Scenario', 'Scenario'), ('Discom_station', 'Dscmstn'), ('Ebus_schedule', 'Ebsscdl')], default=None, max_length=100),
        ),
    ]
