# Generated by Django 5.0.2 on 2024-04-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_datatable_doctype_scenario_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='created_by',
        ),
        migrations.AddField(
            model_name='scenario',
            name='assignment_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='exclusions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
