# Generated by Django 4.2.6 on 2024-04-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_delete_existing_scenarios_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="description",
            field=models.CharField(blank=True, null=True),
        )
    ]
