# Generated by Django 4.2.6 on 2024-05-09 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_scenario_description_alter_project_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='docType',
            field=models.TextField(choices=[('Schedule', 'Schedule'), ('Depot', 'Depot'), ('Terminal', 'Terminal'), ('Scenario', 'Scenario'), ('Scenario_Schedule', 'Scenario_Schedule'), ('DepotTerminalDistanceMatrix', ' DepotTerminalDistanceMatrix'), ('TerminalDepotDistanceMatrix', 'TerminalDepotDistanceMatrix'), ('Discom_station', 'Dscmstn'), ('Ebus_schedule', 'Ebsscdl')], default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='TerminalDepotDistanceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.depot')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='DepotTerminalDistanceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.depot')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.terminal')),
            ],
        ),
    ]
