# Generated by Django 4.2.6 on 2024-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_create_depot_and_terminal"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistanceMatrix",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "start_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "start_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "end_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "end_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "distance",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
            ],
        ),
    ]
