# Generated by Django 4.2.6 on 2024-05-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_create_distance_matrix_from_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('long_name', models.CharField(max_length=200, null=True)),
                ('oem', models.CharField(max_length=100, null=True)),
                ('bus_dimension', models.CharField(max_length=100, null=True)),
                ('gross_vehicle_weight', models.FloatField(null=True)),
                ('air_conditioning', models.CharField(null=True)),
                ('seating_capacity', models.IntegerField(null=True)),
                ('bus_cost', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('charger_type', models.CharField(max_length=50, null=True)),
                ('power_consumption', models.FloatField(null=True)),
                ('battery_capacity', models.IntegerField(null=True)),
                ('battery_cost', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChargerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50, null=True, unique=True)),
                ('long_name', models.CharField(max_length=100, null=True, unique=True)),
                ('oem', models.CharField(max_length=100, null=True)),
                ('charger_type', models.CharField(max_length=50, null=True)),
                ('charger_capacity', models.IntegerField(null=True)),
                ('charger_cost', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
            ],
        ),
    ]
