# Generated by Django 4.2.6 on 2024-05-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_terminalsummary_depotterminalmap_depotsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotterminalmap',
            name='depot_summary_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depot_terminal_sum', to='main.depotsummary'),
        ),
    ]
