# Generated by Django 4.2.6 on 2024-06-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_busmodel_curb_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPowerConsumptionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route_no', models.CharField(null=True)),
                ('start_min', models.IntegerField(null=True)),
                ('end_min', models.IntegerField(null=True)),
                ('start_odo', models.IntegerField(null=True)),
                ('end_odo', models.IntegerField(null=True)),
                ('start_soc', models.IntegerField(null=True)),
                ('end_soc', models.IntegerField(null=True)),
                ('passenger_load', models.FloatField(null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_consumption', to='main.project')),
                ('short_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_consupt', to='main.busmodel')),
            ],
        ),
    ]
