# Generated by Django 4.2.6 on 2024-06-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_historypowerconsumptionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerScenario',
            fields=[
                ('scenario_id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_scenario', to='main.project')),
            ],
        ),
        migrations.AddField(
            model_name='historypowerconsumptionmodel',
            name='scenario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='power_schedule', to='main.powerscenario'),
            preserve_default=False,
        ),
    ]
