# Generated by Django 4.2.6 on 2024-07-06 22:44

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_powerscenario_historypowerconsumptionmodel_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingAnalysisScenario',
            fields=[
                ('scenario_id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('requestdata', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('result', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charging_scenario', to='main.project')),
            ],
        ),
    ]
