# Generated by Django 4.2.6 on 2024-08-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_htcable_meteringpanel_rmu_transformer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTPanel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description_of_item', models.CharField(null=True)),
                ('unit', models.CharField(null=True)),
                ('voltage', models.IntegerField(null=True)),
                ('current', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
            ],
        ),
    ]
