# Generated by Django 4.2.6 on 2024-08-22 18:44

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_ltpanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignEbusScenario',
            fields=[
                ('scenario_id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('design_requestdata', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('design_result', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_ebus_scenario', to='main.project')),
            ],
        ),
    ]
